### ISSUE TITLE
[fix] ostk python import error in virtual environments

### ISSUE THREAD

**Issue by viconnex** [open-space-collective/open-space-toolkit-astrodynamics#398]
## Bug description
Hello! Thanks a lot for sharing this very powerful library!
OSTk dependencies work when installed in a python based docker container.

However, I get **import errors** when I simply `pip install open-space-toolkit-astrodynamics` in a python virtual environment:

```
> from ostk.physics.unit import Angle
Traceback (most recent call last)
  File "./ostk-project/main.py", line 1, in <module>
    from ostk.physics.unit import Angle
  File "./ostk-project/.venv/lib/python3.11/site-packages/ostk/physics/__init__.py", line 3, in <module>
    from ostk.io import *
  File "./ostk-project/.venv/lib/python3.11/site-packages/ostk/io/__init__.py", line 3, in <module>
    from ostk.core import *
  File "./ostk-project/.venv/lib/python3.11/site-packages/ostk/core/__init__.py", line 3, in <module>
    from .OpenSpaceToolkitCorePy import *
ModuleNotFoundError: No module named 'ostk.core.OpenSpaceToolkitCorePy'
```

## Steps to reproduce
1. Buy a macbook
2. Create a local python virtual environment
```
pyenv local 3.11.3
python -m venv .venv
source .venv/bin/activate
```
4. Install dependency `pip install open-space-toolkit-astrodynamics==8.2.0`
5. Import ostk in a python shell
```
python
> from ostk.physics.unit import Angle
```

## Expected behavior
No error when importing modules.

## Additional context
I'm on Mac OS Sonoma 14.4.1

Thank you for your help!

**Comment by aybeshlikyan** [comment]
@viconnex Did you ever figure out how to fix this? I'm running in to the same issue.

**Comment by iorihu2001** [comment]
> Hi [@aybeshlikyan](https://github.com/aybeshlikyan)! Indeed that is the issue, the python libraries were compiled for x86 and that is likely the issue. You could build and compile it yourself for ARM, as we have support for ARM as well, the packages are just not published.
> 
> Alternatively, I would recommend using Docker if that's possible.

This problem persists on x86 systems even after installing the library using 'pip install open-space-toolkit-astrodynamics'; the test code still throws the same error:ModuleNotFoundError: No module named 'ostk.core.OpenSpaceToolkitCorePy'
